ALTER TABLE "Profile" ADD COLUMN IF NOT EXISTS "missionSupporting" TEXT;
ALTER TABLE "Profile" ADD COLUMN IF NOT EXISTS "approach" JSONB;
ALTER TABLE "Profile" ADD COLUMN IF NOT EXISTS "ctaHeading" TEXT;
ALTER TABLE "Profile" ADD COLUMN IF NOT EXISTS "ctaBody" TEXT;
ALTER TABLE "Profile" ADD COLUMN IF NOT EXISTS "ctaButtonLabel" TEXT;
ALTER TABLE "Profile" ADD COLUMN IF NOT EXISTS "ctaButtonHref" TEXT;
